#
name: Create and release deployment archives

on: [push]

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: Archive quickstart Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'tar'
          filename: 'quickstart.tar.gz'
          path: example/quickstart
      - name: Archive production Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'tar'
          filename: 'production.tar.gz'
          path: example/production
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: 'quickstart.tar.gz,production.tar.gz'
          allowUpdates: true
          tag: "archive"
          replacesArtifacts: true

